reserved chache keys issues

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -22,7 +22,7 @@ env:
     ~/.rustup
     ~/.cargo/bin/   
   COMPONENT: clippy,rustfmt # NOTE: if you change COMPONENT, also increase the CACHE_VERSION!
-  CACHE_VERSION: 24
+  CACHE_VERSION: 25
 
 
 jobs:
@@ -52,7 +52,7 @@ jobs:
       - run: ls -1lh ~/.cargo/bin/
     
           
-  build:
+  dependencies:
     runs-on: ubuntu-latest
     needs: preperation
     steps:
@@ -68,7 +68,7 @@ jobs:
     - uses: actions/checkout@v4 
     - id: cache-cargo
       name: Restore cargo cache if exists
-      uses: actions/cache/restore@v3
+      uses: actions/cache@v3
       with:
         path: ${{ env.CARGO_CACHE_PATH }}
         key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
@@ -81,20 +81,38 @@ jobs:
     - run: ls -1lh ~/.cargo/registry/cache/
     - run: ls -1lh ~/.cargo/git/db/
     - run: ls -1lh target/   
-    - name: Save to cargo cache
-      uses: actions/cache/save@v3
-      if: always()
-      with:
-        path: ${{ env.CARGO_CACHE_PATH }}
-        key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
-    # If the tests fail, then at least we have a cache...
-    - name: cargo build
-      run: cargo build
-    - name: Build related test but no execution
-      run: cargo test --no-run
-    - name: Run tests
-      run: cargo test run
-            
+  
+  build:
+    needs: [dependencies]
+    runs-on: ubuntu-latest
+    env:
+      CARGO_TERM_COLOR: always
+    steps:
+     - run: export RUSTFLAGS="${{ env.RUSTFLAGS }}"
+     - id: cache-rustup
+       name: Obtain Rust toolchain
+       uses: actions/cache/restore@v3
+       with:
+         path: ${{ env.RUSTUP_CACHE_PATH }}
+         key: toolchain-${{ env.RUST_UP_DEFAULT }}-v${{ env.CACHE_VERSION }}-
+     - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
+       run: echo 'Failed to retrieve cache';exit 1
+     - id: cache-cargo
+       name: Set up cargo cache
+       uses: actions/cache/restore@v3
+       continue-on-error: false
+       with:
+         path: ${{ env.CARGO_CACHE_PATH }}
+         key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
+     - run: echo steps.cache-cargo.outputs.cache-hit := ${{ steps.cache-cargo.outputs.cache-hit }}
+     - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
+       run: echo 'Failed to retrieve cargo cache';exit 1  
+     # The actual job
+     - name: cargo build
+       run: cargo build
+     - name: Run tests
+       run: cargo test run
+         
   fmt:
     needs: [preperation]
     runs-on: ubuntu-latest
